### ISSUE TITLE
[BUG] Does not work with Pathfinder v10

### ISSUE THREAD

**Issue by Asothin** [AngryBeaver/bsa-pf1#2]
Pathfinder v10 and newer, changes how items are handled and breaks the module.
- When creating new items "New Recipe" and "Any Of" no longer appear.
- Editing existing recipes does not allow removing of items. 
- Minor formatting changes to text fields for code and editing recipes.

Tested on:
Pathfinder v10.4
Foundry v11 Build 315

**Comment by AngryBeaver** [comment]
thx, for the feedback. I ll have a look.

**Comment by AngryBeaver** [comment]
allright could not been fixed within the bsa-x implementation as create Item had not yet been in the system-interface part. Usually the most systems behave the same "a Dialog window" but pf1 now has an own application for it.

So for now it is system depended parked inside beavers-crafting as well as some css fixes.

beavers-crafting 3.5.5 has been released to taggle your issue.

**Comment by Asothin** [comment]
Nice, thank you very much! Works well. There is a slight bug during the "Create New Item" dialogue, where if you change the name field, and the "Recipe" or "AnyOf" is selected it switches back to type "Loot". But that's a very minor issue.

Really appreciate the fix! :)
